name: PR Build

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  call-build:
    if: ${{ github.event.label.name == 'build' }}
    name: Build
    uses: ./.github/workflows/build.yml